// get confirmation user
export const GET_CONFIRMATION_USER_REQUEST = 'GET_CONFIRMATION_USER_REQUEST';
export const GET_CONFIRMATION_USER_SUCCESS = 'GET_CONFIRMATION_USER_SUCCESS';
export const GET_CONFIRMATION_USER_FAILED = 'GET_CONFIRMATION_USER_FAILED';

// change password user
export const CHANGE_PASSWORD_USER_REQUEST = 'CHANGE_PASSWORD_USER_REQUEST';
export const CHANGE_PASSWORD_USER_SUCCESS = 'CHANGE_PASSWORD_USER_SUCCESS';
export const CHANGE_PASSWORD_USER_FAILED = 'CHANGE_PASSWORD_USER_FAILED';
