export const GET_ALL_PODCAST_REQUEST = 'GET_ALL_PODCAST_REQUEST';
export const GET_ALL_PODCAST_SUCCESS = 'GET_ALL_PODCAST_SUCCESS';
export const GET_ALL_PODCAST_FAILED = 'GET_ALL_PODCAST_FAILED';

// get Podcast from user following
export const GET_PODCAST_BY_USER_FOLLOWING_REQUEST = 'GET_PODCAST_BY_USER_FOLLOWING_REQUEST';
export const GET_PODCAST_BY_USER_FOLLOWING_SUCCESS = 'GET_PODCAST_BY_USER_FOLLOWING_SUCCESS';
export const GET_PODCAST_BY_USER_FOLLOWING_FAILED = 'GET_PODCAST_BY_USER_FOLLOWING_FAILED';

// get detail podcast
export const GET_DETAIL_PODCAST_REQUEST = 'GET_DETAIL_PODCAST_REQUEST';
export const GET_DETAIL_PODCAST_SUCCESS = 'GET_DETAIL_PODCAST_SUCCESS';
export const GET_DETAIL_PODCAST_FAILED = 'GET_DETAIL_PODCAST_FAILED';
// get content podcast
export const GET_CONTENT_PODCAST_REQUEST = 'GET_CONTENT_PODCAST_REQUEST';
export const GET_CONTENT_PODCAST_SUCCESS = 'GET_CONTENT_PODCAST_SUCCESS';
export const GET_CONTENT_PODCAST_FAILED = 'GET_CONTENT_PODCAST_FAILED';
// delete podcast
export const DELETE_PODCAST_REQUEST = 'DELETE_PODCAST_REQUEST';
export const DELETE_PODCAST_SUCCESS = 'DELETE_PODCAST_SUCCESS';
export const DELETE_PODCAST_FAILED = 'DELETE_PODCAST_FAILED';
