// follow user
export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST';
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS';
export const USER_FOLLOW_FAILED = 'USER_FOLLOW_FAILED';

// unfollow user

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST';
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS';
export const USER_UNFOLLOW_FAILED = 'USER_UNFOLLOW_FAILED';
// get relationship

export const USER_RELATIONSHIP_REQUEST = 'USER_RELATIONSHIP_REQUEST';
export const USER_RELATIONSHIP_SUCCESS = 'USER_RELATIONSHIP_SUCCESS';
export const USER_RELATIONSHIP_FAILED = 'USER_RELATIONSHIP_FAILED';

// like post
export const USER_LIKE_POST_REQUEST = 'USER_LIKE_POST_REQUEST';
export const USER_LIKE_POST_SUCCESS = 'USER_LIKE_POST_SUCCESS';
export const USER_LIKE_POST_FAILED = 'USER_LIKE_POST_FAILED';
// unlike post
export const USER_UNLIKE_POST_REQUEST = 'USER_UNLIKE_POST_REQUEST';
export const USER_UNLIKE_POST_SUCCESS = 'USER_UNLIKE_POST_SUCCESS';
export const USER_UNLIKE_POST_FAILED = 'USER_UNLIKE_POST_FAILED';

// getStatusLikePost
export const USER_STATUSPOST_REQUEST = 'USER_STATUSPOST_REQUEST';
export const USER_STATUSPOST_SUCCESS = 'USER_STATUSPOST_SUCCESS';
export const USER_STATUSPOST_FAILED = 'USER_STATUSPOST_FAILED';
// commentPost
export const USER_COMMENT_POST_REQUEST = 'USER_COMMENT_POST_REQUEST';
export const USER_COMMENT_POST_SUCCESS = 'USER_COMMENT_POST_SUCCESS';
export const USER_COMMENT_POST_FAILED = 'USER_COMMENT_POST_FAILED';
// get comment post
export const USER_GET_COMMENT_POST_REQUEST = 'USER_GET_COMMENT_POST_REQUEST';
export const USER_GET_COMMENT_POST_SUCCESS = 'USER_GET_COMMENT_POST_SUCCESS';
export const USER_GET_COMMENT_POST_FAILED = 'USER_GET_COMMENT_POST_FAILED';

//get total like count post
export const GET_TOTAL_LIKECOUNT_REQUEST = 'GET_TOTAL_LIKECOUNT_REQUEST';
export const GET_TOTAL_LIKECOUNT_SUCCESS = 'GET_TOTAL_LIKECOUNT_SUCCESS';
export const GET_TOTAL_LIKECOUNT_FAILED = 'GET_TOTAL_LIKECOUNT_FAILED';
