// register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
// login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
// logout
export const USER_LOGOUT = 'USER_LOGOUT';
// upload file

export const USER_UPLOADFILE_REQUEST = 'USER_UPLOADFILE_REQUEST';
export const USER_UPLOADFILE_SUCCESS = 'USER_UPLOADFILE_SUCCESS';
export const USER_UPLOADFILE_FAILED = 'USER_UPLOADFILE_FAILED';

// getProfile

export const USER_GETPROFILE_REQUEST = 'USER_GETPROFILE_REQUEST';
export const USER_GETPROFILE_SUCCESS = 'USER_GETPROFILE_SUCCESS';
export const USER_GETPROFILE_FAILED = 'USER_GETPROFILE_FAILED';

// updateProfile

export const USER_UPDATEPROFILE_REQUEST = 'USER_UPDATEPROFILE_REQUEST';
export const USER_UPDATEPROFILE_SUCCESS = 'USER_UPDATEPROFILE_SUCCESS';
export const USER_UPDATEPROFILE_FAILED = 'USER_UPDATEPROFILE_FAILED';

// search user by username

export const USER_SEARCH_USERNAME_REQUEST = 'USER_SEARCH_USERNAME_REQUEST';
export const USER_SEARCH_USERNAME_SUCCESS = 'USER_SEARCH_USERNAME_SUCCESS';
export const USER_SEARCH_USERNAME_FAILED = 'USER_SEARCH_USERNAME_FAILED';

// get other user profile

export const USER_GET_OTHER_PROFILE_REQUEST = 'USER_GET_OTHERPROFILE_REQUEST';
export const USER_GET_OTHER_PROFILE_SUCCESS = 'USER_GET_OTHER_PROFILE_SUCCESS';
export const USER_GET_OTHER_PROFILE_FAILED = 'USER_GET_OTHER_PROFILE_FAILED';

// get relationship

export const USER_GET_RELATIONSHIP_REQUEST = 'USER_GET_RELATIONSHIP_REQUEST';
export const USER_GET_RELATIONSHIP_SUCCESS = 'USER_GET_RELATIONSHIP_SUCCESS';
export const USER_GET_RELATIONSHIP_FAILED = 'USER_GET_RELATIONSHIP_FAILED';
